name: Bench
on:
  workflow_dispatch:
    inputs:
      benchmark:
        description: Which benchmark to run
        required: false
        default: '.*'
      iterations:
        description: Number of measurement iterations
        required: false
        default: '3'
      size:
        description: Size of data set, comma delimited for multiple
        required: false
        default: '1000000'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Build and test with Maven
      run: |
        mvn compile exec:exec -Djmh.benchmark=${{ github.event.inputs.benchmark }} -Djmh.iterations=${{ github.event.inputs.iterations }} -Djmh.params="size=${{ github.event.inputs.size }}"
    - name: Archive jmh reports
      uses: actions/upload-artifact@v2
      with:
        name: jmh-report
        path: target/jmh-report
    - name: Checkout wiki
      uses: actions/checkout@v2
      with:
        repository: ${{ github.repository }}.wiki
        path: wiki
    - name: Replace wiki code blocks
      run: |
        cd wiki
        $GITHUB_WORKSPACE/src/main/sh/replace.sh $GITHUB_WORKSPACE/target/jmh-report/*
        # TODO is it possible to set from whoever triggered the job?
        git config user.name $GITHUB_ACTOR
        git config user.email github-actions@github.com
        git add .
        git commit -m "updated benchmarks for $GITHUB_WORKFLOW-$GITHUB_RUN_NUMBER"
        git push
