name: Bench
on:
  workflow_dispatch:
    inputs:
      benchmark:
        description: Which benchmark to run
        required: false
        default: '.*'
      iterations:
        description: Number of measurement iterations
        required: false
        default: '3'
      warmup-iterations:
        description: Number of warmup iterations
        required: false
        default: '3'
      size:
        description: Size of data set, comma delimited for multiple
        required: false
        default: '1,10,100,1000,10000,100000,1000000,10000000'

jobs:
  bench:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [8, 9] #[7, 8, 11, 16, 17-ea]
        os: [ubuntu-latest] #[ubuntu-18.04, windows-2019, macos-10.15]
      fail-fast: false
    name: Test JDK ${{ matrix.java }}, ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
        distribution: 'adopt'
        cache: maven
    - name: Build and test with Maven
      run: |
        mvn compile exec:exec -Dmaven.compiler.source=${{ matrix.java }} -Dmaven.compiler.target=${{ matrix.java }} -Djmh.benchmark=${{ github.event.inputs.benchmark }} -Djmh.iterations=${{ github.event.inputs.iterations }} -Djmh.warmupIterations=${{ github.event.inputs.warmup-iterations }} -Djmh.params="size=${{ github.event.inputs.size }}"
    - name: Archive jmh reports
      uses: actions/upload-artifact@v2
      with:
        name: jmh-report
        path: target/jmh-report
    - name: Checkout wiki
      uses: actions/checkout@v2
      with:
        repository: ${{ github.repository }}.wiki
        path: wiki
    - name: Replace wiki code blocks
      run: |
        cd wiki
        $GITHUB_WORKSPACE/src/main/sh/replace.sh $GITHUB_WORKSPACE/target/jmh-report/*
        # TODO is it possible to set from whoever triggered the job?
        git config user.name $GITHUB_ACTOR
        git config user.email github-actions@github.com
        git add .
        git commit -m "updated benchmarks for $GITHUB_WORKFLOW-$GITHUB_RUN_NUMBER JDK ${{ matrix.java }} on ${{ matrix.os }}"
        git push
