name: Bench
on:
  workflow_dispatch:
    inputs:
      benchmakr:
        description: Which benchmark to run
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Build and test with Maven
      run: |
        mvn test
    - name: Archive jmh reports
      uses: actions/upload-artifact@v2
      with:
        name: jmh-report
        path: target/jmh-report
