name: Bench
on:
  workflow_dispatch:
    inputs:
      benchmark:
        description: Which benchmark to run
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Build and test with Maven
      run: |
        mvn test
    - name: Archive jmh reports
      uses: actions/upload-artifact@v2
      with:
        name: jmh-report
        path: target/jmh-report
    - name: Checkout wiki
      uses: actions/checkout@v2
      with:
        repository: ${{ github.repository }}.wiki
        path: ../wiki
    - name: Replace wiki code blocks
      run: |
        cd ../wiki
        $GITHUB_WORKSPACE/replace.sh $GITHUB_WORKSPACE/target/jmh-report/*



