name: Bench
on:
  workflow_dispatch:
    inputs:
      benchmark:
        description: Which benchmark to run (regex)
        required: false
      iteration-time:
        description: Time spent for each measurement/warmup iteration
        required: false
        default: '2'
      iterations:
        description: Number of measurement iterations
        required: false
        default: '15'
      warmup-iterations:
        description: Number of warmup iterations
        required: false
        default: '10'
      size:
        description: Size of data set, comma delimited for multiple
        required: false
        default: '1,10,100,1000,10000,100000,1000000,10000000'
      publish:
        description: Should the results be published?
        required: false
        default: 'false'
      extra-flag:
        description: Extra flag passed to JMH
        required: false
      extra-value:
        description: Extra value passed to JMH
        required: false

jobs:
  bench:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [8, 11, 14, 17]
        os: [ubuntu-latest] #[ubuntu-18.04, windows-2019, macos-10.15]
      fail-fast: false
    name: Test JDK ${{ matrix.java }}, ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3.3.0
      with:
        java-version: ${{ matrix.java }}
        distribution: 'adopt'
        cache: maven
    - name: Build and test with Maven
      run: mvn compile exec:exec
        -Dmaven.compiler.source=${{ matrix.java }}
        -Dmaven.compiler.target=${{ matrix.java }}
        -Djmh.benchmark=${{ github.event.inputs.benchmark }}
        -Djmh.measurementTime=${{ github.event.inputs.iteration-time }}
        -Djmh.iterations=${{ github.event.inputs.iterations }}
        -Djmh.warmupIterations=${{ github.event.inputs.warmup-iterations }}
        -Djmh.warmupTime=${{ github.event.inputs.iteration-time }}
        -Djmh.params="size=${{ github.event.inputs.size }}"
        -Djmh.extra.flag=${{ github.event.inputs.extra-flag }}
        -Djmh.extra.value=${{ github.event.inputs.extra-value }}
    - name: Archive jmh reports
      uses: actions/upload-artifact@v2
      with:
        name: JDK.${{ matrix.java }}
        path: target/jmh-report
  combine:
    needs: bench
    runs-on: ubuntu-latest
    name: Combine the results
    steps:
      - uses: actions/checkout@v2
      - name: Retrieve saved results
        uses: actions/download-artifact@v2
        with:
          path: target
      - name: Combine results into one file
        run: $GITHUB_WORKSPACE/src/main/sh/combine.sh $GITHUB_WORKSPACE/target
      - name: Archive combined jmh report
        uses: actions/upload-artifact@v2
        with:
          name: all
          path: target/all.txt
  publish:
    if: github.event.inputs.publish == 'true'
    needs: combine
    runs-on: ubuntu-latest
    name: Update the wiki
    steps:
    - uses: actions/checkout@v2
    - name: Checkout wiki
      uses: actions/checkout@v2
      with:
        repository: ${{ github.repository }}.wiki
        path: wiki
    - name: Retrieve saved results
      uses: actions/download-artifact@v2
      with:
        name: all
        path: target
    - name: Replace wiki code blocks
      working-directory: wiki
      run: $GITHUB_WORKSPACE/src/main/sh/replace.sh $GITHUB_WORKSPACE/target/all.txt
    - name: Push changes
      working-directory: wiki
      run: |
        # TODO is it possible to set from whoever triggered the job?
        git config user.name $GITHUB_ACTOR
        git config user.email github-actions@github.com
        git add .
        git commit -m "updated benchmarks for $GITHUB_WORKFLOW-$GITHUB_RUN_NUMBER"
        git push
